// <auto-generated />
using EVA3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVA3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231206154039_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EVA3.Models.Music", b =>
                {
                    b.Property<int>("IdCancion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancion"), 1L, 1);

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCancion");

                    b.ToTable("TblMusic");
                });

            modelBuilder.Entity("EVA3.Models.PlayList", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaylistId");

                    b.ToTable("TblPlayList");
                });

            modelBuilder.Entity("EVA3.Models.PlayListMusic", b =>
                {
                    b.Property<int>("PlayListId")
                        .HasColumnType("int");

                    b.Property<int>("MusicId")
                        .HasColumnType("int");

                    b.HasKey("PlayListId", "MusicId");

                    b.HasIndex("MusicId");

                    b.ToTable("TblRelPlayListMusic");
                });

            modelBuilder.Entity("EVA3.Models.PlayListMusic", b =>
                {
                    b.HasOne("EVA3.Models.Music", "music")
                        .WithMany("playListMusics")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVA3.Models.PlayList", "playList")
                        .WithMany("playListMusics")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("music");

                    b.Navigation("playList");
                });

            modelBuilder.Entity("EVA3.Models.Music", b =>
                {
                    b.Navigation("playListMusics");
                });

            modelBuilder.Entity("EVA3.Models.PlayList", b =>
                {
                    b.Navigation("playListMusics");
                });
#pragma warning restore 612, 618
        }
    }
}
